name: C++ CI

on:
  push:
    branches:
      - speedup
  pull_request:
    branches:
      - speedup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: speedup

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y zlib1g zlib1g-dev

    - name: Build
      working-directory: src/
      run: make -f Makefile_linux -j

    - name: Test
      working-directory: src/
      run: ./selscan
